name: Deploying hardhat contract
'on':
  pull_request:
      branches: [ dev ]
  push:
      branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3
      
     # Install dependencies
    - name: Install Dependencies
      run: yarn install
      continue-on-error: false
  

    - run: yarn --ignore-scripts
      shell: bash
    - name: Create local node and deploy
      run: |
        yarn hardhat node &
        yarn hardhat run scripts/deploy.js --network localhost
    - name: Run Tests
      run: yarn hardhat test

        
    # Merge to main branch
    - name: Merge to dev
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/dev' # Only merge on successful push to main branch
      run: git merge origin/dev --no-edit
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
        continue-on-error: false
        
        
    #     Slither test
    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      id: slither
      with:
        node-version: 16
        sarif: results.sarif
        fail-on: none

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
